apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookappbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookappbackend
  template:
    metadata:
      labels:
        app: bookappbackend
    spec:
      containers:
        - name: bookappbackend
          image: bookappbackend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
