apiVersion: v1
kind: Service
metadata:
  name: bookappbackend
spec:
  selector:
    app: bookappbackend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30008
  type: LoadBalancer
